### ISSUE TITLE
Registration for Advanced+ missing details / unclear

### ISSUE THREAD

**Issue by OvidiuS** [OvidiuS/Citadel-Swing-Website#23]
It currently just says:  If you are an Advanced WSDC Dancer, please get in touch with us. We have a separate registration process for you. (you can see it on the schedule page, under the Friday Registration item details)

This seems weird to me, why not put in the details there right away? Or at least make it more clear as to what's going on?

**Comment by SwinginSteps** [comment]
We have to provide them with a discount code ... the registration form would be exactly the same :-)
I can't think of another process which would allow advanced+ wsdc dancers to register for free.
Other ideas are welcome

**Comment by OvidiuS** [comment]
@SwinginSteps do you have to personally verify that they are  Advanced+ level before you provide them with the free ticket? Makes, sense, BUT **please note**: you will need to create an ACCESS code not a discount code.  Please see here: https://www.eventbrite.com/support/articles/en_US/How_To/how-to-set-up-access-codes-for-hidden-tickets?lg=en_US

**Comment by SwinginSteps** [comment]
So then, do we need to state anything else on the website or can we consider this point closed?

**Comment by SwinginSteps** [comment]
So the text reads: If you are an Advanced WSDC Dancer, please get in touch with us. We have a separate registration process for you.
Let's add a direct form of contact to this text. Can we make a mailto:info@citadelswing.ro link under the text "get in touch with us"? Or shold we explicitly state that they should write an email at bla ...
Ce parere ai?

**Comment by SwinginSteps** [comment]
Am vorbit cu Lumi and we decided that we can make the advanced+ discount code public, since there is a way to verify each registration that has used this code ... so let's rewrite the text into:
"If you are an Advanced WSDC Dancer, please use the discount code below when registering: csadvfree. Please note that in order for the discount to be applied, you have to enter the code before choosing your ticket. If you have any questions don't hesitate to get in touch with us."
